name: ci

on:
  push:
    # tags:
    #   - "*"
    branches:
      - temp*
env:
  DOCKER_BUILDKIT: 1
  # ubuntu-dind-pnpm-tmp
  IMAGE_NAME: sudorekt/ubuntu-dind-pnpm-tmp
  TEST_TAG: sudorekt/ubuntu-dind-pnpm-tmp:latest

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      #
      - name: Checkout
        uses: actions/checkout@v3
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      #
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      #
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: o-az
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      #
      - name: Test
        env:
          TEST_COMMAND: |
            echo "Print versions..." && \
            docker --version && \
            docker compose version && \
            node --version && \
            pnpm --version && \
            doppler --version
          CONTAINER_NAME: ubuntu-dind-pnpm-tmp
        run: |
          docker run --privileged --rm -it --detach --name $CONTAINER_NAME ${{ env.TEST_TAG }}
          docker exec $CONTAINER_NAME /bin/bash -c $TEST_COMMAND
      #
      # DOCKER HUB: sudorekt/ubuntu-dind-pnpm
      # GITHUB CONTAINER REGISTRY: ghcr.io/o-az/ubuntu-dind-pnpm
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            sudorekt/${{ env.IMAGE_NAME }}:latest
            sudorekt/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}

            ghcr.io/o-az/${{ env.IMAGE_NAME }}:latest
            ghcr.io/o-az/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          #
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
