name: ci

on:
  push:
    # TEMPORARY - UNCOMMENT ME
    # tags:
    #   - "*"

    # TEMPORARY - DELETE ME
    branches:
      - temp-*

env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: ubuntu-dind-pnpm

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      #
      - name: Checkout
        uses: actions/checkout@v3
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      #
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # sudorekt/ubuntu-dind-pnpm:latest
          # sudorekt/ubuntu-dind-pnpm:refs/heads/master
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref }}

  github-container-registry:
    runs-on: ubuntu-latest
    steps:
      #
      - name: Checkout
        uses: actions/checkout@v3
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      #
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # ghcr.io/o-az/ubuntu-dind-pnpm:latest
          # ghcr.io/o-az/ubuntu-dind-pnpm:refs/heads/master
          tags: |
            ghcr.io/${{ github.repository_owner }}/ubuntu-dind-pnpm:latest
            ghcr.io/${{ github.repository_owner }}/ubuntu-dind-pnpm:${{ github.ref }}

  success:
    needs: [docker-hub, github-container-registry]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Success"
